name: ul_fs_health
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  auto_route: ^9.2.2
  bloc: ^8.1.4
  cloud_firestore: ^5.5.1
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.3.4
  firebase_core: ^3.8.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.4
  get_it: ^8.0.3
  intl: ^0.19.0
  json_annotation: ^4.9.0
  email_validator: ^3.0.0
  google_fonts: ^6.2.1

dev_dependencies:
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.14
  flutter_gen_runner: ^5.8.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.9.0

flutter_gen:
  output: lib/gen/
  line_length: 100

  # Optional
  integrations:
    flutter_svg: true

  fonts:
    outputs:
      package_parameter_enabled: true

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter_Black.ttf
        - asset: assets/fonts/inter/Inter_BlackItalic.ttf
          style: italic
        - asset: assets/fonts/inter/Inter_ExtraBold.ttf
        - asset: assets/fonts/inter/Inter_ExtraBoldItalic.ttf
          style: italic
        - asset: assets/fonts/inter/Inter_Bold.ttf
        - asset: assets/fonts/inter/Inter_BoldItalic.ttf
          style: italic
        - asset: assets/fonts/inter/Inter_Light.ttf
        - asset: assets/fonts/inter/Inter_LightItalic.ttf
          style: italic
        - asset: assets/fonts/inter/Inter_Regular.ttf
        - asset: assets/fonts/inter/Inter_Italic.ttf
          style: italic

flutter_intl:
  enabled: true
  arb-dir: lib/l10n
  template-arb-file: intl_en.arb
  output-localization-file: S.dart
