// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTH1OlFJvkYbj6XkUtzDt5gy055JilsDo',
    appId: '1:950114511919:web:c23e7f761b06acea06eada',
    messagingSenderId: '950114511919',
    projectId: 'ul-fs-health-app',
    authDomain: 'ul-fs-health-app.firebaseapp.com',
    storageBucket: 'ul-fs-health-app.firebasestorage.app',
    measurementId: 'G-20G5G3N5BG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOOjhvXOVMBILxYRKYNZXyzJ_c7MrgNvI',
    appId: '1:950114511919:android:200bd521cbf60cd806eada',
    messagingSenderId: '950114511919',
    projectId: 'ul-fs-health-app',
    storageBucket: 'ul-fs-health-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxYibE0Ue_LMosY3p8iHrhUfWpNIBAC38',
    appId: '1:950114511919:ios:62aa72fb7e89a16006eada',
    messagingSenderId: '950114511919',
    projectId: 'ul-fs-health-app',
    storageBucket: 'ul-fs-health-app.firebasestorage.app',
    iosBundleId: 'com.example.ulFsHealth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxYibE0Ue_LMosY3p8iHrhUfWpNIBAC38',
    appId: '1:950114511919:ios:62aa72fb7e89a16006eada',
    messagingSenderId: '950114511919',
    projectId: 'ul-fs-health-app',
    storageBucket: 'ul-fs-health-app.firebasestorage.app',
    iosBundleId: 'com.example.ulFsHealth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTH1OlFJvkYbj6XkUtzDt5gy055JilsDo',
    appId: '1:950114511919:web:b60dd762fd37f52706eada',
    messagingSenderId: '950114511919',
    projectId: 'ul-fs-health-app',
    authDomain: 'ul-fs-health-app.firebaseapp.com',
    storageBucket: 'ul-fs-health-app.firebasestorage.app',
    measurementId: 'G-667SZ63PKP',
  );

}